name: Get Schedule
run-name: Get Schedule

on:
  workflow_dispatch:
  repository_dispatch:
    types: [schedule_update]

permissions:
  contents: write

concurrency:
  group: 'schedule'
  cancel-in-progress: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Get Schedule File
        uses: nicolasiannarilli/action-sharepoint-download@v1.0.0
        with:
          site_url: 'https://leipziggutenbergschule.sharepoint.com/sites/StudioprojektB'
          library_folder: 'Freigegebene Dokumente/Regie'
          target_folder: 'download'
          sharepoint_user: ${{ secrets.SHAREPOINT_USN }}
          sharepoint_password: ${{ secrets.SHAREPOINT_PWD }}

      - name: Convert XLSX to CSV
        uses: JoeSiu/xlsx-to-csv-action@1.0.0 # This should stay at @1.0.0, since the @v1.0.3 version broke the entire pipeline
        with:
          inputFile: './download/Sendeablauf.xlsx'
          filter: '{ "Länge": "Length", "Kürzel": "Code", "Kapitel": "Chapter" }'

      - name: Parse CSV
        run: deno run --allow-read --allow-write .github/workflows/csvToSchedule.ts

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: schedule.json

  commit:
    runs-on: ubuntu-latest
    needs: download
    strategy:
      matrix:
        branch: [main, dev]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: src/assets

      - name: Move File to Proper Location
        run: |
          cd src/assets
          mv artifact/schedule.json schedule.json

      - name: Commit File to ${{ matrix.branch }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Schedule
