name: Get Schedule
run-name: Get Schedule

on:
  repository_dispatch:
    types: [schedule_update]

permissions:
  contents: write

concurrency:
  group: 'schedule'
  cancel-in-progress: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Get Schedule File
        uses: nicolasiannarilli/action-sharepoint-download@v1.0.0
        with:
          site_url: 'https://leipziggutenbergschule.sharepoint.com/sites/StudioprojektB'
          library_folder: 'Freigegebene Dokumente/Regie'
          target_folder: 'download'
          sharepoint_user: ${{ secrets.SHAREPOINT_USN }}
          sharepoint_password: ${{ secrets.SHAREPOINT_PWD }}

      - name: Convert XLSX to CSV
        uses: JoeSiu/xlsx-to-csv-action@1.0.0
        with:
          inputFile: './download/Sendeablauf.xlsx'
          filter: '{ "Länge": "Length", "Kürzel": "Code", "Kapitel": "Chapter" }'

      - name: Parse CSV
        run: deno run --allow-read --allow-write .github/workflows/csvToSchedule.ts

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: schedule.json

  main:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: src/assets/

      - name: Commit File to Main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Schedule

  dev:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: src/assets/

      - name: Commit File to Dev
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Schedule
